name: Main Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyCleanArchitecture.sln
      working-directory: MyCleanArchitecture

    - name: Build
      run: dotnet build --no-restore -c Release MyCleanArchitecture.sln
      working-directory: MyCleanArchitecture

  inspection:
    needs: [build]
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: List contents of the current directory
      #   run: ls -la
      #   shell: bash
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # [3.1.x, 5.0.x, 6.0.x, 7.0.x, 8.0.xVPN
      - name: Restore
        run: dotnet restore MyCleanArchitecture/MyCleanArchitecture.sln
        # ReSharper CLI. Анализатор не определяет наличие комментариев к свойствам и методам, поэтому в добавок он использует еще правила от StyleCop
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: MyCleanArchitecture/MyCleanArchitecture.sln
          # UnusedMember.Global - свойства, методы, поля и объекты которые не используются
          # SuggestVarOrType_SimpleTypes - вместо var явно использовать тип
          # ClassNeverInstantiated.Global - созданный класс нигде не используется
          ignoreIssueType: |
            UnusedAutoPropertyAccessor.Global
            ArrangeNamespaceBody
            UseCollectionExpression
            UnusedMember.Global
            ConvertToPrimaryConstructor
            UnusedMember.Global
            PropertyCanBeMadeInitOnly.Global
            SuggestVarOrType_SimpleTypes
            ClassNeverInstantiated.Global
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}