name: Main Workflow

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Укажите нужную версию .NET Core

    # - name: Check style core
    #   run: dotnet build -c Release -warnaserror

    # - name: Restore dependencies
    #   run: dotnet restore

    - name: Restore dependencies
      run: dotnet restore MyCleanArchitecture.sln 
      working-directory: MyCleanArchitecture

    - name: Build
      run: dotnet build --no-restore -c Release MyCleanArchitecture.sln
      working-directory: MyCleanArchitecture

    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal