name: Extract Number from Branch Name

on:
  create:
    # Ограничение событий только созданием веток
    branches-ignore:
      - 'main'
      - 'master'
      
jobs:
  extract-number:
    runs-on: ubuntu-latest
    # Условие, которое гарантирует выполнение только при создании ветки
    if: github.ref_type == 'branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Extract Number from Branch Name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          NUMBER=$(echo "$BRANCH_NAME" | grep -o -E '[0-9]+')
          echo "Extracted number: $NUMBER"