name: Extract Issue Number from Branch Name

on:
  push:
    branches:
      - '*'
    branches-ignore:
      - main
      - dev

jobs:
  extract-issue-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and Print Issue Number
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -o -E '^[0-9]+')
          echo "Issue number extracted from branch name: $ISSUE_NUMBER"
          echo "Issue number is $ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Use Issue Number in Another Step
        run: |
          echo "Using Issue Number: $ISSUE_NUMBER"