name: Branch Workflow

on:
  create:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name != 'dev' && github.ref_name != 'main'
    steps:
      - name: Extract Issue Number from Branch Name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '^\d+')
          echo "Issue number extracted from branch name is $ISSUE_NUMBER"
          # Здесь добавьте команды для выполнения действий с номером задачи