name: ReSharper CLI Analysis

on: [push]

jobs:
  inspection:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List contents of the current directory
        run: ls -la
        shell: bash        
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # [3.1.x, 5.0.x, 6.0.x, 7.0.x, 8.0.xVPN
      - name: Restore
        run: dotnet restore MyCleanArchitecture/MyCleanArchitecture.sln
        # ReSharper CLI. Анализатор не определяет наличие комментариев к свойствам и методам
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: MyCleanArchitecture/MyCleanArchitecture.sln
          ignoreIssueType: |
            UnusedAutoPropertyAccessor.Global
            ArrangeNamespaceBody
            UseCollectionExpression
            UnusedMember.Global
            ConvertToPrimaryConstructor
            UnusedMember.Global # член класса (например, метод, свойство, поле или событие), который не используется
            PropertyCanBeMadeInitOnly.Global 
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}